---
- name: Remove conflicting Rust APT packages
  ansible.builtin.apt:
    name:
      - rustc
      - cargo
      - libstd-rust-1.75
      - libstd-rust-dev
    state: absent
    purge: true
    autoremove: true

- name: Determine if cargo is already installed
  ansible.builtin.stat:
    path: "{{ local_home }}/.cargo/bin/cargo"
  register: rustup_cargo_bin
  become: true
  become_user: "{{ local_user }}"

- name: Install rustup toolchain manager
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail;
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
      | sh -s -- -y --no-modify-path
    executable: /bin/bash
  args:
    creates: "{{ local_home }}/.cargo/bin/cargo"
  become: true
  become_user: "{{ local_user }}"
  when: not rustup_cargo_bin.stat.exists
  changed_when: true
